---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: helm-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: helm-operator
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: helm-operator
        annotations:
          prometheus.io/scrape: "true"
      spec:
        serviceAccountName: helm-operator
        containers:
        - name: helm-operator
          # There are no ":latest" images for helm-operator. Find the most recent
          # release or image version at https://hub.docker.com/r/weaveworks/helm-operator/tags
          # and replace the tag here.
          image: docker.io/fluxcd/helm-operator:1.0.0-rc4
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 3030
          livenessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
          # Include this if you need to mount a customised known_hosts or ssh_config
          # file; you'll also need the volume declared above.
          # - name: sshdir
          #   mountPath: /root/.ssh
          #   readOnly: true
          # - name: git-key
          #   mountPath: /etc/fluxd/ssh
          # - name: repositories-yaml
          #   mountPath: /var/fluxd/helm/repository
          # - name: repositories-cache
          #   mountPath: /var/fluxd/helm/repository/cache
          # - name: helm-tls-certs
          #   mountPath: /etc/fluxd/helm
          #   readOnly: true
          # - name: helm-tls-ca
          #   mountPath: /etc/fluxd/helm-ca
          #   readOnly: true
          args:
          # How to find Tiller
          - --tiller-namespace=kube-system
          # Comment out to to establish validated TLS connections against Tiller
          # - --tiller-tls-ca-cert-path=/etc/fluxd/helm-ca/ca.crt
          # - --tiller-tls-enable=true
          # - --tiller-tls-key-path=/etc/fluxd/helm/tls.key
          # - --tiller-tls-cert-path=/etc/fluxd/helm/tls.crt
          # - --tiller-tls-verify=true
          # - --tiller-tls-ca-cert-path=/etc/fluxd/helm-ca/ca.crt