namespace: flux-system
resources:
  - namespace.yaml
  - rbac.yaml
  - psp.yaml
bases:
  - ../base/flux/
  - ../base/memcached/
  - github.com/fluxcd/helm-operator//deploy
patchesStrategicMerge:
  - flux-patch.yaml
  - helm-operator-patch.yaml
